# Generated by Django 2.1.3 on 2018-11-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181106_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CAM', 'Camiseta'), ('LIC', 'Licra')], max_length=3),
        ),
    ]
